Unroll loop support for free0, free1 dimension
ROCmSoftwarePlatform/Tensile pull request #1145
Opened 2020-08-24 19:39 UTC by ramjana

-support to unroll in Free0,Free1 dimension.

2020-09-01 17:43 UTC, zaliu commented
@ramjana Please resolve conflicts so that CI can run.  Thanks.

2020-09-03 17:23 UTC, AlexBrownAMD requested changes

2020-09-03 17:23 UTC, AlexBrownAMD commented on Tensile/KernelWriter.py
> +              k1.append(localReads)
This section could be restructured: if using scheduleLastIterAlg, the loop doesn't need to run at all, and putting the check before the loop would also make it easier to read.

2020-09-03 17:23 UTC, AlexBrownAMD commented on Tensile/KernelWriter.py
> +          if not (self.scheduleLastIterAlg):
There's a number of these checks in this section of code, maybe a refactor like using modules could help with ease of reading in this section.

2020-09-03 17:23 UTC, AlexBrownAMD commented on Tensile/KernelWriter.py
> +          if packAB.items():
Same if condition as above

2020-09-03 17:23 UTC, AlexBrownAMD commented on Tensile/KernelWriter.py
> +    if self.scheduleLastIterAlg == 1:
This should probably go in a module

2020-09-03 17:23 UTC, AlexBrownAMD commented on Tensile/KernelWriter.py
> +              numReadsToSched  = 3 if (numReadsToSched>3) else numReadsToSched  # cap it to 3  to allow other instructions
should if (i==0) be elif? Can this block be combined with the similar if/else block above it?

2020-09-08 19:35 UTC, cgmillette requested changes
Builds are failing, plus general code structure comments

2021-02-23 17:19 UTC, zaliu commented
Inactivity.  Can reopen later.

2021-02-23 17:19 UTC, closed without merging