Initial implementation support for aldebaran
ROCmSoftwarePlatform/Tensile pull request #1300
Opened 2021-03-11 02:49 UTC by yoichiyoshida

Add initial support for aldebaran (gfx90a)

- adds initial support for double precision MFMA
- adds alignment restrictions for 64 bit wide register instructions for gfx90a compatibility
- adds MFMA bf16_1k instruction support

2021-03-16 17:35 UTC, zaliu requested changes
In the interest of not blocking gfx10 merging for too long, **flat addressing tests in extended CI can be disabled for now.**  We need to remember to fix this issue though.  At one point in the past, we relied on flat addressing for very large matrices; not anymore.  We might need flat addressing in the future for different reasons.  Thanks.

2021-03-16 20:28 UTC, AlexBrownAMD commented on Tensile/KernelWriterAssembly.py
> +    vgprIdx = ((vgprIdx+1)//2)*2
Leftover todo stuff

2021-03-16 20:28 UTC, AlexBrownAMD commented on Tensile/Source/client/main.cpp
> +        //listeners.addListener(std::make_shared<HardwareMonitorListener>(args));
Is it intended to always disable this?

2021-03-16 20:28 UTC, AlexBrownAMD commented on Tensile/Source/client/main.cpp
> +        //listeners.addListener(std::make_shared<HardwareMonitorListener>(args));
(Also I think the default global param was changed)

2021-03-16 23:25 UTC, sdquiring approved these changes
Looks good to me.

2021-03-17 15:36 UTC, AlexBrownAMD approved these changes

2021-03-18 21:52 UTC, zaliu approved these changes
Thanks for the good work @yoichiyoshida and @AlexBrownAMD!

2021-03-18 21:57 UTC, merged