Add compiler launcher environment variables
ROCmSoftwarePlatform/Tensile pull request #1331
Opened 2021-04-20 05:18 UTC by cgmb

This change adds support for two environment variables: `Tensile_ASM_COMPILER_LAUNCHER` and `Tensile_CXX_COMPILER_LAUNCHER`, which serve a similar purpose as the [`CMAKE_<LANG>_COMPILER_LAUNCHER`](https://cmake.org/cmake/help/latest/envvar/CMAKE_LANG_COMPILER_LAUNCHER.html) variable in CMake.

With this change and `export Tensile_ASM_COMPILER_LAUNCHER=/usr/local/bin/ccache`, the cached assembly kernels are retreived almost instantly when building rocBLAS. The source kernels remain a major cause of slow builds, however.

`export Tensile_CXX_COMPILER_LAUNCHER=/usr/local/bin/ccache` will invoke ccache when building `/src/rocBLAS/build/release/Tensile/Kernels.cpp`, though the result always seems to be a cache miss. I don't think the miss has anything to do with my implementation of this feature. The Kernels.cpp file is 46 MB and preprocessing with -E results in 514 MB of output, so it's difficult to debug. In any case, perhaps another compiler launcher (like sccache) will be able to handle that beast.

2021-04-20 15:39 UTC, cgmb commented
@JeremyAdamHart answered many of my questions about Tensile while I was making this change, though I will admit my understanding is still quite limited.

2021-04-20 15:57 UTC, AlexBrownAMD approved these changes
lgtm

2021-04-20 16:31 UTC, zaliu requested changes
Pending @bragadeesh's explicit approval.  Thanks.

2021-04-20 16:46 UTC, cgmb commented
This isn't an urgent change. It's a feature for developers using Tensile and it should have no impact on the kernels, so there's little difference in merging this week or next. Feel free to ignore this until Monday.

2021-04-20 16:59 UTC, pfultz2 commented
This should be a flag that can be passed from cmake(in the `TensileCreateLibraryFiles` function), so the user only needs to set `CMAKE_CXX_COMPILER_LAUNCHER` for it to work with tensile.

2021-04-20 18:10 UTC, cgmb commented
My understanding of Tensile is limited, so I tried to define this feature in a way that it would have no impact on anybody unless they specifically enable it. My change purposefully avoids changing behaviour for any existing users, but it may very well be that existing users would benefit from different behaviour. I just opted for the smallest, safest change I could make. (That said, nothing here precludes adding support for `CMAKE_CXX_COMPILER_LAUNCHER` later, either.)

In terms of broader changes, I would love to dig into the Tensile / rocBLAS build and try to clean it up a bit. I think we could cut the rocBLAS compile times on developer workstations and the CI by nearly order of magnitude if we took a step back and reworked the way the Tensile part of the build is defined. However, I'm neither a rocBLAS nor a Tensile developer, so my time to work on that is in short supply.

2021-04-25 03:07 UTC, cgmb commented
The source kernels never get a cache hit with ccache due to non-deterministic output from hipcc -E. I've opened SWDEV-283320 to track the issue.

2021-04-26 16:40 UTC, cgmb commented
The CI now supports ccache. If you'd like to try out these changes, you can add the `ci:ccache` label to this PR.

2021-05-03 03:45 UTC, merged