Refactor vgpr occupancy calculation for Unified Register Files
ROCmSoftwarePlatform/Tensile pull request #1371
Opened 2021-06-23 04:27 UTC by jichangjichang

2021-06-23 06:47 UTC, rosenrodt requested changes
Please check the failing tests in Tensile/Tests/unit/test_KernelWriterAssembly.py

Some of the relevant functions are made either a static method of `KernelWriterAssembly` or independent from `KernelWriterAssembly` is because of ease of test. So you may want to revisit the your changes that moved those function into `KernelWriterAssembly`.

2021-06-23 06:47 UTC, rosenrodt commented on Tensile/KernelWriterAssembly.py
> +  class VgprOccupancyCurve:
Any particular motivation to move the class into `KernelWriterAssembly`?

2021-06-23 08:21 UTC, jichangjichang reviewed
> Please check the failing tests in Tensile/Tests/unit/test_KernelWriterAssembly.py
> 
> Some of the relevant functions are made either a static method of `KernelWriterAssembly` or independent from `KernelWriterAssembly` is because of ease of test. So you may want to revisit the your changes that moved those function into `KernelWriterAssembly`.

This test should be removed.
Occupancy table is different between different GCN version.
Test should not treat it as a static table.

2021-06-23 09:06 UTC, rosenrodt commented
> This test should be removed.
> Occupancy table is different between different GCN version.
> Test should not treat it as a static table.

The updated occupancy calculator still needs to be proven correct one way or the other. Removing the tests won't help with that goal.

You can use `pytest.mark.parametrize` decorator for arch-dependent tests. There is also a predefined pytest fixture `useGlobalParameters` in conftest.py to allow you to access `globalParameters` from within the test. That should be enough

2021-06-25 09:45 UTC, jichangjichang commented
> > This test should be removed.
> > Occupancy table is different between different GCN version.
> > Test should not treat it as a static table.
> 
> The updated occupancy calculator still needs to be proven correct one way or the other. Removing the tests won't help with that goal.
> 
> You can use `pytest.mark.parametrize` decorator for arch-dependent tests. There is also a predefined pytest fixture `useGlobalParameters` in conftest.py to allow you to access `globalParameters` from within the test. That should be enough

Designed has been changed. Occupancy is calculated when runtime but not refer to a table.
The CI test scope also extend for UnifiedRegisterFiles.

2021-06-25 09:47 UTC, jichangjichang commented
> > This test should be removed.
> > Occupancy table is different between different GCN version.
> > Test should not treat it as a static table.
> 
> The updated occupancy calculator still needs to be proven correct one way or the other. Removing the tests won't help with that goal.
> 
> You can use `pytest.mark.parametrize` decorator for arch-dependent tests. There is also a predefined pytest fixture `useGlobalParameters` in conftest.py to allow you to access `globalParameters` from within the test. That should be enough

2021-06-25 09:52 UTC, jichangjichang commented
> Please check the failing tests in Tensile/Tests/unit/test_KernelWriterAssembly.py
> 
> Some of the relevant functions are made either a static method of `KernelWriterAssembly` or independent from `KernelWriterAssembly` is because of ease of test. So you may want to revisit the your changes that moved those function into `KernelWriterAssembly`.

@rosenrodt need your review to unblock the change requested

2021-06-25 09:55 UTC, rosenrodt approved these changes
Nice. Looks good

2021-06-29 09:45 UTC, jichangjichang commented
rocblas-test pass on gfx908 and gfx90a

2021-06-30 22:14 UTC, zaliu approved these changes

2021-07-01 01:37 UTC, merged